[package]
name = "zqa"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"
arrow-array = "52.2.0"
arrow-schema = "52.2.0"
libsqlite3-sys = "^0.32"
rusqlite = "0.34.0"
dotenv = "0.15.0"
rag = { path = "../rag/"}
pdftools = { path = "../pdftools/"}
reqwest = "0.12.14"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.44.1"
ftail = "0.2.1"
log = "0.4.27"
indicatif = "0.17.11"

[[bin]]
name = "zqa"
path = "src/chain.rs"
