name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: sudo apt install protobuf-compiler
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
      env:
        ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_MODEL: claude-sonnet-4-20250514
        OPENAI_EMBEDDING_MODEL: text-embedding-3-small
        MAX_CONCURRENT_REQUESTS: 5
